using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace FitMemory.Api.Data;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(
        FitMemoryDbContext db,
        CancellationToken cancellationToken = default)
    {
        if (db.Database.IsSqlite())
        {
            await db.Database.EnsureCreatedAsync(cancellationToken);
            await DatabaseSchemaUpgrader.UpgradeAsync(db);
            return;
        }

        if (!db.Database.IsNpgsql())
        {
            await db.Database.EnsureCreatedAsync(cancellationToken);
            return;
        }

        if (await FitMemoryTablesExistAsync(db, cancellationToken))
        {
            await UpgradePostgresAsync(db, cancellationToken);
            return;
        }

        var databaseCreator = db.GetService<IRelationalDatabaseCreator>();
        await databaseCreator.CreateTablesAsync(cancellationToken);
        await UpgradePostgresAsync(db, cancellationToken);
    }

    private static Task UpgradePostgresAsync(
        FitMemoryDbContext db,
        CancellationToken cancellationToken)
    {
        return db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "UserAccounts" ADD COLUMN IF NOT EXISTS "PasswordResetCodeHash" text NULL;
            ALTER TABLE "UserAccounts" ADD COLUMN IF NOT EXISTS "PasswordResetExpiresAtUnix" bigint NULL;
            ALTER TABLE "UserAccounts" ADD COLUMN IF NOT EXISTS "PasswordResetAttempts" integer NOT NULL DEFAULT 0;
            ALTER TABLE "StyleBoardItems" ADD COLUMN IF NOT EXISTS "MaterialSummary" text NOT NULL DEFAULT '';
            ALTER TABLE "StyleBoardItems" ADD COLUMN IF NOT EXISTS "MaterialEvidence" text NOT NULL DEFAULT '';
            ALTER TABLE "StyleBoardItems" ADD COLUMN IF NOT EXISTS "IsInStudio" boolean NOT NULL DEFAULT true;
            ALTER TABLE "StyleBoardItems" ADD COLUMN IF NOT EXISTS "IsSaved" boolean NOT NULL DEFAULT false;
            ALTER TABLE "OrderHistoryItems" ADD COLUMN IF NOT EXISTS "MaterialSummary" text NULL;
            ALTER TABLE "OrderHistoryItems" ADD COLUMN IF NOT EXISTS "MaterialEvidence" text NULL;
            ALTER TABLE "OrderHistoryItems" ADD COLUMN IF NOT EXISTS "ImportFingerprint" character varying(64) NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_OrderHistoryItems_UserProfileId_ImportFingerprint"
                ON "OrderHistoryItems" ("UserProfileId", "ImportFingerprint");
            CREATE TABLE IF NOT EXISTS "FavoriteOutfits" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserProfileId" integer NOT NULL,
                "Title" character varying(160) NOT NULL,
                "AnalysisJson" text NOT NULL,
                "ItemsJson" text NOT NULL,
                "CreatedAt" bigint NOT NULL,
                CONSTRAINT "FK_FavoriteOutfits_UserProfiles_UserProfileId"
                    FOREIGN KEY ("UserProfileId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_FavoriteOutfits_UserProfileId_CreatedAt"
                ON "FavoriteOutfits" ("UserProfileId", "CreatedAt");
            """,
            cancellationToken);
    }

    private static async Task<bool> FitMemoryTablesExistAsync(
        FitMemoryDbContext db,
        CancellationToken cancellationToken)
    {
        var connection = db.Database.GetDbConnection();
        var openedHere = connection.State != ConnectionState.Open;

        if (openedHere)
        {
            await connection.OpenAsync(cancellationToken);
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText =
                "SELECT to_regclass('public.\"UserProfiles\"') IS NOT NULL";
            var result = await command.ExecuteScalarAsync(cancellationToken);
            return result is true;
        }
        finally
        {
            if (openedHere)
            {
                await connection.CloseAsync();
            }
        }
    }
}
